config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients

  scope :with_all_inputed_ingredients, ->(ingredient_list) {
    joins(:ingredients)
      .group("recipes.id")
      .having(ingredient_list.map { "SUM(CASE WHEN ingredients.name ILIKE ? THEN 1 ELSE 0 END) > 0" }.join(" AND "), *ingredient_list.map { |ingredient| "%#{ingredient}%" })
  }

  scope :with_max_cooking_time, ->(max_cook_time) {
    where('cook_time <= ?', max_cook_time)
  }

  scope :with_max_preparation_time, ->(max_prep_time) {
    where('prep_time <= ?', max_prep_time)
  }

  scope :with_min_ratings, ->(min_ratings) {
    where('ratings >= ?', min_ratings)
  }

  scope :order_by_ratings, ->() {
    order(ratings: :desc)
  }

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  require 'pagy/extras/metadata'
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    begin 
      recipe_search_service = RecipeSearchService.new(params)
      @pagy, @recipes = pagy(recipe_search_service.call)

      respond_to do |format|
        format.html
        format.json {
          render json: {
            recipes_html: render_to_string(partial: 'recipe_list', locals: { recipes: @recipes }, formats: [:html]),
            pagination_html: render_to_string(partial: 'pagination', locals: { pagy: @pagy }, formats: [:html])
          }
        }
      end
    
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "No recipes found."
      @pagy, @recipes = pagy(Recipe.none)
      render json: { error: "No recipes found" }, status: :not_found

    rescue => e
      flash.now[:alert] = "An error occurred: #{e.message}"
      @pagy, @recipes = pagy(Recipe.none)
      Rails.logger.error("Error fetching recipes: #{e.message}")
      render json: { error: "An error occurred: #{e.message}" }, status: :internal_server_error
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watsfodinna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_pagination.html.erb
<%== pagy_nav(pagy) if pagy.pages > 1 %>

app/views/recipes/_recipe_list.html.erb
<% recipes.each do |recipe| %>
    <li data-ratings="<%= recipe.ratings %>" data-cook-time="<%= recipe.cook_time %>" data-prep-time="<%= recipe.prep_time %>">
    <strong>Title:</strong> <%= recipe.title %><br>
    <strong>Cook Time:</strong> <%= recipe.cook_time %> minutes<br>
    <strong>Prep Time:</strong> <%= recipe.prep_time %> minutes<br>
    <strong>Ingredients:</strong>
    <ul>
        <% recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient.name %></li>
        <% end %>
    </ul>
    <strong>Ratings:</strong> <%= recipe.ratings %><br>
    <strong>Author:</strong> <%= recipe.author %><br>
    </li>
    <br><br>
<% end %>

app/views/recipes/index.html.erb
<% flash.each do |key, message| %>
  <div><%= message %></div>
<% end %>

<h1>Recipes</h1>
<%= form_with(url: recipes_path, method: :get, local: true) do %>
  <%= label_tag :ingredients, "Enter ingredients (comma-separated):" %>
  <%= text_field_tag :ingredients, '', size: 100 %>
  <div>Optional:</div>
  <div>
    <%= label_tag :max_cook_time, "Max cooking time (in min):" %>
    <%= text_field_tag :max_cook_time %>
    <br>
    <%= label_tag :max_cook_time, "Max preparation time (in min):" %>
    <%= text_field_tag :max_prep_time %>
    <br>
    <%= label_tag :min_ratings, "Min rating:" %>
    <%= text_field_tag :min_ratings %>
  </div>
  
  <%= submit_tag "Search" %>
<% end %>
<br>
<div id="pagination">
    <%= render "pagination", pagy: @pagy %>
</div>
<%== pagy_info(@pagy) %>
<br>
<div data-controller="recipe-sort">
    <button data-action="click->recipe-sort#toggleSort" data-sort-by="ratings" data-current-order="<%= params[:order] == 'desc' ? 'asc' : 'desc' %>">Sort by Ratings</button>
    <button data-action="click->recipe-sort#toggleSort" data-sort-by="cook_time" data-current-order="<%= params[:order] == 'asc' ? 'desc' : 'asc' %>">Sort by Cook Time</button>
    <button data-action="click->recipe-sort#toggleSort" data-sort-by="prep_time" data-current-order="<%= params[:order] == 'asc' ? 'desc' : 'asc' %>">Sort by Prep Time</button>
</div>
<br>
<div  id="recipe-list">
    <%= render "recipe_list", recipes: @recipes %>
</div>